// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the definition of an abbreviation
	// (GET /abbreviation/{abbr})
	GetAbbreviation(ctx echo.Context, abbr string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAbbreviation converts echo context to params.
func (w *ServerInterfaceWrapper) GetAbbreviation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "abbr" -------------
	var abbr string

	err = runtime.BindStyledParameterWithLocation("simple", false, "abbr", runtime.ParamLocationPath, ctx.Param("abbr"), &abbr)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter abbr: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAbbreviation(ctx, abbr)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/abbreviation/:abbr", wrapper.GetAbbreviation)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4xTwYrbMBD9FTHt0cTudimLboGFEmhh6fbW5qDI41iLpVGlcSAE/3sZJdt1Gh/2FGXm",
	"6Wnem+cTWPKRAgbOoE+QbY/elON6t0t4cIYdhR+YI4WMUo+JIiZ2WFDWMO4pHeXcYrbJRbkAGn72qF67",
	"ijrFPSoz44QK+BgRNGROLuxhqsCjCXJcJLs038sVjMdlIum8j2X6V6HdC1qGSUoudHTLvH7aqI5SYV3b",
	"RN8No5qbmNXvsWnuvpRuOPqsHp2VhknHlbzteJCn3i4/baCCA6Z8fuHTqlk1Io0iBhMdaPhcShVEw33Z",
	"Rz0XVJ/k3yT1PbL8yOpKa9OChq/I62v90STjkTFl0L+WvJvTKybVudCCWAK6DAGvxoMgoYKEf0aXsAXN",
	"acTqkjCZ5X+vtwI+56xIuWuakjAKjKFMb2IcnD1Le8ky02nG9zFhBxo+1G+Rri95rhfDXJZ5LfF5tBZz",
	"7sZhOKqOxtDepmSq4L65XwjA3JpAfL5fQpRH7418JGJ5YWyxc8EVKHXKhJsgmr2s4IoUtmXijOmwvKBv",
	"ZM2gHvGAA0WPgdVzwUIFYxpAQ88cdV0Pgusps35oHhqYttPfAAAA//9Kr3/ICAQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
